<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yQIigMR' shared service.

return $this->privates['.service_locator.yQIigMR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ArticleController::editor' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.J7dFThm', 'get_ServiceLocator_J7dFThmService.php', true],
    'App\\Controller\\ArticleController:editor' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.J7dFThm', 'get_ServiceLocator_J7dFThmService.php', true],
], [
    'App\\Controller\\ArticleController::editor' => '?',
    'App\\Controller\\ArticleController::index' => '?',
    'App\\Controller\\ArticleController:editor' => '?',
    'App\\Controller\\ArticleController:index' => '?',
]);
