#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

app_article:
  path: /article
  controller: App\Controller\ArticleController::index


menu_item:
  path: /menu/item
  controller: App\Controller\MenuController::index

edit_article:
  path: /article/edit
  controller: App\Controller\MenuController

