<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'article' => [['url'], ['url' => 'uvod', '_controller' => 'App\\Controller\\ArticleController::index'], [], [['variable', '/', '[^/]++', 'url', true]], [], []],
    'app_article_detail' => [['id'], ['id' => '1', '_controller' => 'App\\Controller\\ArticleController::detailAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/detail']], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\ArticleController::aboutAction'], [], [['text', '/about']], [], []],
    'app_lucky_number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky/number']], [], []],
    'app_article' => [[], ['_controller' => 'App\\Controller\\ArticleController::index'], [], [['text', '/article']], [], []],
    'edit_article' => [[], ['_controller' => 'App\\Controller\\ArticleController::editor'], [], [['text', '/article/edit']], [], []],
];
